// GENERATED by scripts/generate_hackathon_types.py — do not edit by hand.
// Regenerate: uv run python scripts/generate_hackathon_types.py
//
// Source of truth: packages/nest-marketplace/nest_marketplace/adapter.py
// Display helpers live in hackathon-display.ts.


export type Tag = "agent-authored" | "human-authored";

export type LayerKey =
  | "transport"
  | "communication"
  | "identity"
  | "registry"
  | "auth"
  | "trust"
  | "payments"
  | "coordination"
  | "negotiation"
  | "memory"
  | "privacy"
  | "datafacts"
  | "unclassified";

export interface SubmissionAuthor {
  handle: string;
  avatar_url: string;
  profile_url: string;
  kind: "agent" | "human";
}

export interface JudgeScore {
  correctness: number | null;
  test_rigor: number | null;
  api_fit: number | null;
  docs_quality: number | null;
  novelty: number | null;
  persona_fidelity: number | null;
  total: number | null;
  notes: string | null;
}

/** Numeric range for a single rubric dimension (judges score 1..5). */
export const SCORE_DIMENSION_MAX = 5;
/** Maximum possible total across the six dimensions. */
export const SCORE_TOTAL_MAX = 30;

export interface Submission {
  id: string;
  pr_number: number;
  title: string;
  short_description: string | null;
  body_markdown: string;
  layer: LayerKey;
  branch: string;
  author: SubmissionAuthor;
  pr_url: string;
  diff_url: string;
  additions: number | null;
  deletions: number | null;
  changed_files: number | null;
  created_at: string;
  score: JudgeScore | null;
  tag: Tag;
}

export interface LayerStats {
  key: Exclude<LayerKey, "unclassified">;
  label: string;
  blurb: string;
  submission_count: number;
  top_score: number | null;
  is_open: boolean;
}

export interface MarketplaceStats {
  total_submissions: number;
  unique_participants: number;
  layers_covered: number;
  layers_total: number;
  total_lines_added: number | null;
  total_files_changed: number | null;
}

export interface Dataset {
  generated_at: string;
  stats: MarketplaceStats;
  layers: LayerStats[];
  submissions: Submission[];
}

export const KNOWN_LAYER_KEYS = [
  "transport",
  "communication",
  "identity",
  "registry",
  "auth",
  "trust",
  "payments",
  "coordination",
  "negotiation",
  "memory",
  "privacy",
  "datafacts",
] as const;
