# SPDX-License-Identifier: Apache-2.0
"""Generate TypeScript hackathon types from nest_marketplace.adapter dataclasses.

Usage::

    uv run python scripts/generate_hackathon_types.py
    uv run python scripts/generate_hackathon_types.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from nest_marketplace.adapter import KNOWN_LAYERS

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "apps" / "nest-dashboard" / "src" / "lib" / "hackathon-types.ts"

HEADER = """\
// GENERATED by scripts/generate_hackathon_types.py — do not edit by hand.
// Regenerate: uv run python scripts/generate_hackathon_types.py
//
// Source of truth: packages/nest-marketplace/nest_marketplace/adapter.py
// Display helpers live in hackathon-display.ts.
"""


def generate() -> str:
    layer_keys = "\n  | ".join(f'"{layer}"' for layer in KNOWN_LAYERS)
    known_layers_ts = ",\n  ".join(f'"{layer}"' for layer in KNOWN_LAYERS)
    return f"""{HEADER}

export type Tag = "agent-authored" | "human-authored";

export type LayerKey =
  | {layer_keys}
  | "unclassified";

export interface SubmissionAuthor {{
  handle: string;
  avatar_url: string;
  profile_url: string;
  kind: "agent" | "human";
}}

export interface JudgeScore {{
  correctness: number | null;
  test_rigor: number | null;
  api_fit: number | null;
  docs_quality: number | null;
  novelty: number | null;
  persona_fidelity: number | null;
  total: number | null;
  notes: string | null;
}}

/** Numeric range for a single rubric dimension (judges score 1..5). */
export const SCORE_DIMENSION_MAX = 5;
/** Maximum possible total across the six dimensions. */
export const SCORE_TOTAL_MAX = 30;

export interface Submission {{
  id: string;
  pr_number: number;
  title: string;
  short_description: string | null;
  body_markdown: string;
  layer: LayerKey;
  branch: string;
  author: SubmissionAuthor;
  pr_url: string;
  diff_url: string;
  additions: number | null;
  deletions: number | null;
  changed_files: number | null;
  created_at: string;
  score: JudgeScore | null;
  tag: Tag;
}}

export interface LayerStats {{
  key: Exclude<LayerKey, "unclassified">;
  label: string;
  blurb: string;
  submission_count: number;
  top_score: number | null;
  is_open: boolean;
}}

export interface MarketplaceStats {{
  total_submissions: number;
  unique_participants: number;
  layers_covered: number;
  layers_total: number;
  total_lines_added: number | null;
  total_files_changed: number | null;
}}

export interface Dataset {{
  generated_at: string;
  stats: MarketplaceStats;
  layers: LayerStats[];
  submissions: Submission[];
}}

export const KNOWN_LAYER_KEYS = [
  {known_layers_ts},
] as const;
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated output differs from the committed file.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=OUTPUT,
        help=f"Output path (default: {OUTPUT})",
    )
    args = parser.parse_args(argv)

    content = generate()
    if args.check:
        if not args.out.exists():
            print(f"Missing {args.out}; run without --check to generate.", file=sys.stderr)
            return 1
        existing = args.out.read_text(encoding="utf-8")
        if existing != content:
            print(f"{args.out} is out of date; run generate_hackathon_types.py", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date.")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
