"""Real-LLM ResonanceBFT consensus demo — LLM agents form opinions, the protocol agrees.

Each agent's OPINION is generated by an LLM (or a deterministic mock), sealed at
``participate()``, and the ``n−f`` quorum commit + genuine-vs-superficial audit run
DETERMINISTICALLY over the sealed vectors. This is the "transformer-at-the-edge,
deterministic core" design: the LLM's nondeterminism is frozen at seal time (per agent),
so it informs perception but never forks the commit.

Run (offline, deterministic mock LLM — no keys, no network):
    python demo.py
    python demo.py --scales 4,7,12,20

Run with a REAL LLM (nondeterministic — a demonstration, not a test):
    # subscription CLI, NO API KEY (uses your local claude/codex/agy login). Lowest/fastest
    # models are plenty — the deterministic core does not need a frontier model:
    python demo.py --backend claude --model haiku --scales 4,7
    python demo.py --backend codex --scales 4
    python demo.py --backend agy --model "Gemini 3.5 Flash (Low)" --scales 4
    # local, no key: install ollama, `ollama pull llama3.2`
    python demo.py --backend ollama --model llama3.2 --scales 4,7
    # any OpenAI-compatible endpoint:
    OPENAI_API_KEY=... OPENAI_BASE_URL=https://api.openai.com/v1 \
        python demo.py --backend openai --model gpt-4o-mini

Optional dense (attention) embedding on the semantic axis so the stance audit bites:
    python demo.py --embed fastembed        # pip install fastembed   (no torch)

The paper *Can AI Agents Agree?* (Berdoz et al. 2026, arXiv:2603.01213) finds real LLM
Byzantine consensus is unreliable, dominated by LIVENESS failures — which ResonanceBFT
targets with its n−f commit + bounded-round HK convergence. This demo is where you can
watch that play out with real models.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import urllib.request
from collections.abc import Callable
from pathlib import Path
from typing import Any

_PKG = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_PKG))

from nest_core.types import AgentId, Task  # noqa: E402
from nest_plugins_reference.coordination.resonance_bft import (  # noqa: E402
    ResonanceBFT,
    pentadic_summary,
)

LlmFn = Callable[[dict[str, str], str], str]

# ── Personas: distinct leans/angles so the consensus is non-trivial (supporters + dissent) ──
PERSONAS: list[dict[str, str]] = [
    {"name": "Pragmatic engineer", "lean": "support", "angle": "faster delivery with good CI"},
    {"name": "Cautious tech lead", "lean": "oppose", "angle": "risk of breaking main"},
    {"name": "Enthusiastic adopter", "lean": "support", "angle": "it is the modern standard"},
    {"name": "Skeptical veteran", "lean": "oppose", "angle": "we tried this before and it hurt"},
    {"name": "Data-driven analyst", "lean": "support", "angle": "metrics favour shorter cycles"},
    {"name": "User-focused PM", "lean": "support", "angle": "it ships value to users sooner"},
    {"name": "Security-minded reviewer", "lean": "oppose", "angle": "less review time worries me"},
    {"name": "Cost-conscious manager", "lean": "support", "angle": "less overhead, lower cost"},
]

DEFAULT_QUESTION = "Should our team adopt trunk-based development?"


# ── LLM backends ────────────────────────────────────────────────────────────────
def _mock_llm(persona: dict[str, str], question: str) -> str:
    """Deterministic stand-in: a plausible 1-sentence opinion from the persona's lean/angle."""
    lean, angle = persona["lean"], persona["angle"]
    verb = {"support": "approve", "oppose": "reject", "neutral": "hold"}[lean]
    stance = {
        "support": f"I approve — {angle}, so we should adopt it.",
        "oppose": f"I reject this — {angle}, it is too risky to adopt now.",
        "neutral": f"I would hold — {angle}; let us gather more data before we decide.",
    }[lean]
    return f"{stance} ({verb})"


def _ollama_llm(model: str) -> LlmFn:
    def call(persona: dict[str, str], question: str) -> str:
        prompt = (
            f"You are a {persona['name']} whose angle is: {persona['angle']}. "
            f"In ONE or TWO sentences, give your honest opinion on: {question} "
            f"Your general lean is to {persona['lean']} it. Be specific and take a clear stance."
        )
        body = json.dumps({"model": model, "prompt": prompt, "stream": False}).encode()
        req = urllib.request.Request(
            "http://localhost:11434/api/generate",
            data=body,
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=120) as resp:  # noqa: S310 (localhost)
            return json.loads(resp.read())["response"].strip()

    return call


def _openai_llm(model: str) -> LlmFn:
    base = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    key = os.environ.get("OPENAI_API_KEY", "")

    def call(persona: dict[str, str], question: str) -> str:
        prompt = (
            f"You are a {persona['name']} whose angle is: {persona['angle']}. "
            f"In ONE or TWO sentences, give your honest opinion on: {question} "
            f"Your general lean is to {persona['lean']} it. Be specific and take a clear stance."
        )
        body = json.dumps(
            {"model": model, "messages": [{"role": "user", "content": prompt}], "temperature": 0.7}
        ).encode()
        req = urllib.request.Request(
            f"{base}/chat/completions",
            data=body,
            headers={"Content-Type": "application/json", "Authorization": f"Bearer {key}"},
        )
        with urllib.request.urlopen(req, timeout=120) as resp:  # noqa: S310
            return json.loads(resp.read())["choices"][0]["message"]["content"].strip()

    return call


# Locally-authenticated agent CLIs usable as key-free LLM backends. Each shells out to a
# headless one-shot invocation and returns the model's clean text response — exactly like an
# API call, but billed to the interactive subscription login. Model switching is uniform via
# --model where the subscription tier permits it. All three are verified working on this
# machine: claude (Anthropic), codex (ChatGPT account), agy (Antigravity — Gemini/Claude/GPT
# models). `agy models` lists the menu, e.g. "Gemini 3.1 Pro (High)", "Claude Opus 4.6".
_CLI_BACKENDS = ("claude", "codex", "agy")


def _cli_llm(backend: str, model: str) -> LlmFn:
    """Generate opinions via a locally-authenticated subscription CLI — no API key needed.

    Shells out to `claude -p`, `codex exec`, or `agy -p`, dropping the metered API-key env var
    (where one exists) so the CLI uses its interactive login. This is the key-free way to drive
    the consensus with a real frontier model, and supports switching models per backend.
    """
    import subprocess
    import tempfile
    import time

    def call(persona: dict[str, str], question: str) -> str:
        prompt = (
            f"You are a {persona['name']} whose angle is: {persona['angle']}. "
            f"In ONE sentence, give your honest opinion on: {question} "
            f"Your lean is to {persona['lean']} it. Output ONLY the one-sentence opinion, "
            f"nothing else."
        )
        env = dict(os.environ)
        # Isolate each call to a throwaway cwd so no project CLAUDE.md / AGENTS.md / repo file
        # leaks into the prompt — the calls then behave like a bare stateless API. (Claude's
        # `--bare` would also strip global auto-memory, but it forces ANTHROPIC_API_KEY auth,
        # defeating the key-free subscription login, so we keep OAuth + cwd isolation instead.)
        with tempfile.TemporaryDirectory(prefix="rbft_llm_") as cwd:

            def run(argv: list[str], timeout: int) -> subprocess.CompletedProcess[str]:
                # Subscription CLIs occasionally fail a call transiently (rate limits, flaky
                # sockets). Retry with backoff so one hiccup does not poison a whole town run.
                last: Exception | None = None
                for attempt in range(3):
                    try:
                        return subprocess.run(  # noqa: S603
                            argv,
                            capture_output=True,
                            text=True,
                            timeout=timeout,
                            env=env,
                            stdin=subprocess.DEVNULL,
                            cwd=cwd,
                            check=True,
                        )
                    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
                        last = exc
                        if attempt < 2:
                            time.sleep(2.0 * (attempt + 1))
                raise last  # type: ignore[misc]  # unreachable with last=None

            if backend == "claude":
                env.pop("ANTHROPIC_API_KEY", None)
                # --no-session-persistence: no transcript written to disk, cannot be resumed.
                argv = [
                    backend,
                    "-p",
                    prompt,
                    "--no-session-persistence",
                    *(["--model", model] if model else []),
                ]
                return _clean(run(argv, 180).stdout)
            if backend == "agy":  # Antigravity CLI; auth is its own subscription login
                argv = [backend, "-p", prompt, *(["--model", model] if model else [])]
                return _clean(run(argv, 300).stdout)
            # codex prints a session preamble to stdout; -o writes ONLY the final message.
            # model_reasoning_effort=low: a one-sentence opinion needs no deep reasoning, and
            # codex defaults to xhigh (~10x slower) — low keeps each call to a few seconds.
            env.pop("OPENAI_API_KEY", None)
            last = os.path.join(cwd, "last.txt")
            argv = [
                backend,
                "exec",
                "--skip-git-repo-check",
                "-c",
                "model_reasoning_effort=low",
                "-o",
                last,
                *(["-m", model] if model else []),
                prompt,
            ]
            run(argv, 300)
            with open(last, encoding="utf-8") as fh:
                return _clean(fh.read())

    return call


def _clean(text: str) -> str:
    return " ".join(text.strip().splitlines()).strip() or "(no response)"


def make_llm(backend: str, model: str) -> LlmFn:
    if backend == "mock":
        return _mock_llm
    if backend == "ollama":
        return _ollama_llm(model or "llama3.2")
    if backend == "openai":
        return _openai_llm(model or "gpt-4o-mini")
    if backend in _CLI_BACKENDS:  # subscription CLI, no API key
        return _cli_llm(backend, model)
    raise SystemExit(
        f"unknown --backend {backend!r} (use mock|ollama|openai|{'|'.join(_CLI_BACKENDS)})"
    )


def make_embed(kind: str) -> Callable[[str], list[float]] | None:
    if kind == "none":
        return None
    import importlib

    if kind == "fastembed":
        fe = importlib.import_module("fastembed").TextEmbedding("BAAI/bge-small-en-v1.5")
        return lambda t: list(fe.embed([t]))[0].tolist()
    if kind == "model2vec":
        _sm = importlib.import_module("model2vec").StaticModel
        m = _sm.from_pretrained("minishlab/potion-base-8M")
        return lambda t: [float(x) for x in m.encode([t])[0].tolist()]
    raise SystemExit(f"unknown --embed {kind!r} (use none|fastembed|model2vec)")


def _print_outcome(m: dict[str, Any]) -> None:
    print("\n" + pentadic_summary(m))
    cq: dict[str, Any] = m.get("consensus_quality", {})
    fa = cq.get("false_agreement_rate", "n/a (bag-of-words; use --embed fastembed)")
    print(
        f"\nOutcome: {m['status'].upper()}   quorum {m['quorum_size']}/{m['quorum_needed']}"
        f"   (n={m['total_participants']}, f={m['f']})"
    )
    print(f"  consensus_type : {m.get('consensus_type', 'unknown')}")
    print(f"  false_agreement: {fa}")
    print(
        f"  quality        : independence={cq.get('independence_rate', '-')}"
        f"  capitulation={cq.get('capitulation_rate', '-')}"
        f"  collapse={cq.get('disagreement_collapse', '-')}"
    )
    print(
        f"  tampered       : {m.get('tampered_agents', [])}"
        f"   tampered_exceeds_f={m.get('tampered_exceeds_f')}"
    )


def _evil_label(i: int, byzantine: int, garbage: int) -> str:
    if i < byzantine:
        return "[BYZANTINE — tampers seal]"
    if i < byzantine + garbage:
        return "[MALFORMED — garbage vector]"
    return ""


async def run_round(
    title: str,
    question: str,
    opinions: list[str],
    embed_fn: Callable[[str], list[float]] | None,
    backend: str,
    embed_kind: str,
    *,
    byzantine: int = 0,
    garbage: int = 0,
    note: str = "",
) -> dict[str, Any]:
    """One consensus round; injects `byzantine` (broken-seal) and `garbage` (non-finite)
    records AFTER participate() so resolve() must detect them. Returns the outcome metadata."""
    n = len(opinions)
    bar = "=" * 74
    faults = (
        f"byzantine={byzantine}, malformed={garbage}" if (byzantine or garbage) else "no faults"
    )
    print(f"\n{bar}\n {title}   (n={n}, LLM: {backend}, embed: {embed_kind}, {faults})\n{bar}")
    print(f"Question: {question}\nOpinions:")
    agents = [
        ResonanceBFT(AgentId(f"a{i}"), seed=i, expected_n=n, embed_fn=embed_fn) for i in range(n)
    ]
    task = Task(id="llm-consensus", description=question)
    for i, opinion in enumerate(opinions):
        task.metadata[f"eval_a{i}"] = opinion
        print(f"  a{i:<2} {_evil_label(i, byzantine, garbage):<28} {opinion}")

    rnd = await agents[0].propose(task, all_agents=[f"a{i}" for i in range(n)])
    for a in agents:
        await a.participate(rnd)
    # Adversarial injection: mutate the sealed record so the SHA-256 seal no longer matches.
    ev = rnd.metadata["evaluations"]
    for i in range(byzantine):
        sem = ev[f"a{i}"].get("semantic", [0.0])
        ev[f"a{i}"]["semantic"] = [x + 999.0 for x in sem]  # valid numbers, wrong belief
    for i in range(byzantine, byzantine + garbage):
        width = max(1, len(ev[f"a{i}"].get("semantic", [0.0])))
        ev[f"a{i}"]["semantic"] = [float("inf")] * width  # non-finite → schema-invalid

    m = (await agents[0].resolve(rnd)).metadata
    _print_outcome(m)
    if note:
        print(f"  → {note}")
    return m


_ORTHOGONAL = [
    "kittens purr softly indoors",
    "quantum entanglement puzzles physicists",
    "the harvest moon glows orange tonight",
    "tariffs are reshaping global shipping",
    "volcanoes slowly reshape island coastlines",
]

# Adversarial + quality suite — each case is designed (and empirically verified) to exhibit a
# specific behaviour: genuine commit, audit-flagged false/coerced commit, contained evil,
# overwhelmed evil (safety abort), and malformed-record detection.
SUITE: list[dict[str, Any]] = [
    {
        "title": "1. GENUINE consensus",
        "question": "Should we adopt the new deployment policy?",
        "opinions": [
            "approve — the rollout plan is safe and well tested",
            "yes, I support adopting this; the CI gates look solid",
            "approve, this reduces risk and speeds delivery for us",
            "I am in favour — the metrics back it up clearly",
            "approve, this is the right call for the whole team",
            "yes, adopt it; the tradeoffs are acceptable here",
            "approve — well reasoned and genuinely low risk",
        ],
        "note": "aligned honest agents, no faults → clean COMMIT (tampered=[], "
        "false_agreement 0). The baseline to contrast the audit signals against below.",
    },
    {
        "title": "2. FALSE consensus (audit catches it)",
        "question": "Should we approve the budget increase?",
        "opinions": ["approve the budget increase"] * 3 + ["reject the budget increase"] * 3,
        "note": "same proposition, OPPOSITE stance → commits by topic, but the stance audit "
        "flags it (run with --embed fastembed to see false_agreement > 0).",
    },
    {
        "title": "3. MANUFACTURED / coerced consensus",
        "question": "Do you support the initiative?",
        "opinions": _ORTHOGONAL,
        "note": "unrelated opinions → commits a quorum, but the quality audit flags it as NOT "
        "genuine (coerced / capitulated) — the commit is not real agreement.",
    },
    {
        "title": "4. EVIL agents CONTAINED (k ≤ f)",
        "question": "Should we ship the release?",
        "opinions": ["approve, ship the release"] * 7,
        "byzantine": 2,
        "note": "2 Byzantine tamper their sealed records (f=2) → detected + excluded, the honest "
        "quorum still COMMITS, tampered=2.",
    },
    {
        "title": "5. EVIL agents OVERWHELM (k > f) → NO consensus",
        "question": "Should we ship the release?",
        "opinions": ["approve, ship the release"] * 7,
        "byzantine": 3,
        "note": "3 Byzantine > f=2 → tampered_exceeds_f → ABORT. Safety: it refuses to commit "
        "when faults exceed the tolerance, rather than commit a corrupted result.",
    },
    {
        "title": "6. MALFORMED / garbage records",
        "question": "Should we merge the change?",
        "opinions": ["approve, merge it"] * 7,
        "garbage": 2,
        "note": "2 agents submit non-finite (inf) vectors → flagged tampered by schema "
        "validation, excluded; the honest quorum commits.",
    },
]


async def run_suite(
    embed_fn: Callable[[str], list[float]] | None, backend: str, embed_kind: str
) -> None:
    print(
        "\nAdversarial + quality suite. Theme: a COMMIT is not the same as genuine agreement —\n"
        "the protocol commits a coherent n−f quorum, the AUDIT (consensus_type / false_agreement\n"
        "/ quality) tells you whether that commit is real, tampered records are detected and\n"
        "excluded, and it ABORTS (no consensus) when faults exceed the tolerance f."
    )
    for case in SUITE:
        await run_round(
            case["title"],
            case["question"],
            case["opinions"],
            embed_fn,
            backend,
            embed_kind,
            byzantine=case.get("byzantine", 0),
            garbage=case.get("garbage", 0),
            note=case["note"],
        )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--backend",
        default="mock",
        help="mock | ollama | openai | claude | codex | agy "
        "(claude/codex/agy = key-free subscription CLIs)",
    )
    ap.add_argument("--model", default="", help="LLM model name for ollama/openai")
    ap.add_argument("--embed", default="none", help="none | fastembed | model2vec")
    ap.add_argument("--scales", default="4,7,12", help="comma-separated agent counts")
    ap.add_argument("--question", default=DEFAULT_QUESTION)
    ap.add_argument(
        "--suite",
        action="store_true",
        help="run the adversarial + quality suite (genuine / false / coerced / evil / malformed)"
        " instead of the scale sweep",
    )
    args = ap.parse_args()

    embed_fn = make_embed(args.embed)
    if args.suite:
        asyncio.run(run_suite(embed_fn, args.backend, args.embed))
        return

    llm = make_llm(args.backend, args.model)
    scales = [int(s) for s in args.scales.split(",") if s.strip()]
    for n in scales:
        opinions = [llm(PERSONAS[i % len(PERSONAS)], args.question) for i in range(n)]
        asyncio.run(
            run_round(
                f"SCALE: {n} agents",
                args.question,
                opinions,
                embed_fn,
                args.backend,
                args.embed,
            )
        )
    if args.backend == "mock":
        print("\n(Deterministic mock LLM. For real models: --backend ollama|openai.)")


if __name__ == "__main__":
    main()
